ifeq ($(CONFIG_MSM_BT_POWER),m)
KBUILD_CPPFLAGS += -DCONFIG_MSM_BT_POWER
endif

ifeq ($(CONFIG_BT_HW_SECURE_DISABLE), y)
KBUILD_CPPFLAGS += -DCONFIG_BT_HW_SECURE_DISABLE
endif

obj-$(CONFIG_MSM_BT_POWER) += pwr/
